#server:
#  port: 8443
#  ssl:
#    key-store-password: Novo2407
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat

server:
  port: 8080


spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: arkadi
    password: 1234
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: arkadi.sender@gmail.com
    password: Test123!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

# web,root
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

